import {
  faArrowLeft,
  faArrowRight,
  faArrowUpFromBracket,
  faCheck,
  faClockRotateLeft,
  faDesktop,
  faFlag,
  faForwardStep,
  faGear,
  faPlay,
  faRightFromBracket,
  faRightToBracket,
  faRotateLeft,
  faShieldHalved,
  faTrophy,
  faUser,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

import { IFontAwesomeIcon } from '../../utils/models/asset.models';

export const ICONS: IFontAwesomeIcon = {
  apply: faCheck,
  arrow_left: faArrowLeft,
  arrow_right: faArrowRight,
  attack: faForwardStep,
  back: faRotateLeft,
  battle: faShieldHalved,
  cancel: faXmark,
  computer: faDesktop,
  history: faClockRotateLeft,
  human: faUser,
  login: faRightToBracket,
  logout: faRightFromBracket,
  ranking: faTrophy,
  start: faPlay,
  settings: faGear,
  signup: faArrowUpFromBracket,
  surrender: faFlag,
}
